### PR TITLE
(#19) more-link

### PR DESCRIPTION
**Pull request by klepas**
Uses > char in place of an icon.

See #19.

### CODE REVIEW

**Comment by klepas** [comment]
Ugh, I just noticed this module needs to be renamed to just `see-more` — I started work on this before I saw your note in slack re. limiting to `two-words` max for module naming… :S

**Comment by dominikwilkowski** [comment]
Please merge `develop` into this branch to enable the preview.

**Comment by dominikwilkowski** [comment]
merged

**Comment by dominikwilkowski** [comment]
staging: https://64-78596482-gh.circle-artifacts.com/0/tmp/circle-artifacts.XGI3L6o/packages/more-link/tests/site/index.html

**Pull request merged**
