### PR TITLE
Toggle accordion state with props instead of state

### PR DESCRIPTION
**Pull request by alex-page**
@ndavison was having some issues using the accordion state currently and suggested this change. I am going to make some quick changes and a `*-test` branch so we can see the rendered accordion and talk about it.

There are some issues I am noticing already @ndavison :

- The accordion now re renders when the open and close property changes. This means when an external button changes the state of the accordion there is no transition between `open` and `close`. The cause of this issue is that the accordion opens then is rendered instantly, there is no transition between the classes or heights of the element anymore.

I would recommend having a look at how we set up the test component that toggles the accordion state from an external location:
https://github.com/govau/uikit/blob/f69d6e71ca41c7159914d4cbaf8e60764c909c3b/packages/accordion/tests/react/index.js#L7-L34

@mikey0000 I would love to know if this is the issue you are having or something else unrelated.

### CODE REVIEW

**Comment by alex-page** [comment]
> @alex-page with no props set hitting the a href never changed state (open or closed), if I set state I could manipulate it using the react dev tools which would work but the built in a href still would not function as expected, I also saw transition issues as well but only with going from closed to open.

Thanks @mikey0000 can you share what your component code looks like and what version of the accordion you are using.

**Comment by mikey0000** [comment]
```
<AUaccordion
            header="Headline"
            speed={ 250 }
        >
            Some content for this accordion.
        </AUaccordion>
```
master branch of UIKit (f69d6e71ca41c7159914d4cbaf8e60764c909c3b)

also double clicking the href changes the arrows direction but no state change.

**Comment by alex-page** [comment]
That code should be exactly the same as this page:
https://uikit.service.gov.au/packages/accordion/tests/react/

I would check to make sure you don't have any console errors, and you have all the necessary scripts. Have a look at our test folder for how we set up the accordion react component:
https://github.com/govau/uikit/tree/master/packages/accordion/tests/react
https://github.com/govau/uikit/blob/master/packages/accordion/tests/react/index.html
https://github.com/govau/uikit/blob/master/packages/accordion/tests/react/index.js

**Comment by mikey0000** [comment]
Ok ran the test page and that is fine, so clearly something else at play, heres the full storybook story
```
import React, { Fragment } from 'react';

import { storiesOf } from '@storybook/react';
import AUaccordion from '../uikit/packages/accordion/src/js/react';
require('../uikit/packages/accordion/src/sass/_dependencies.scss');


const store = new Store({
    closed: false
});


storiesOf('Accordion', module)

    .add('accordion', () => (
    <Fragment>

        <AUaccordion
            header="Headline"
            speed={ 250 }


        >
            Some content for this accordion.
        </AUaccordion>

    </Fragment>

    ));
```

**Comment by mikey0000** [comment]
Are you able to tell me how state gets set to 'open'? From what I can see so far its never changing the state to open (within this storybook scenario)

**Comment by alex-page** [comment]
Ok @mikey0000 let me know if you are having any more issues always happy to help out 👍

**Comment by mikey0000** [comment]
Hi Alex, I am planning on creating a running fork of UIKIT for use within a public organisation in NZ hence why I have a clone, do you know what is adding the class="js" to the html header? Once I add that it works perfectly, is there a requirement to prefix it?

**Comment by alex-page** [comment]
Awesome to hear. On our documentation site we explain it:

>  Note: Accordion requires feature detection to see if a user has javascript.
>  Please add a `no-js` class on html and replace it with `js` if enabled
>  https://www.paulirish.com/2009/avoiding-the-fouc-v3/

There is a code snippet at the top of all of our pages that changes the `no-js` class to `js`. This means that our components still work when a user does not have javascript or it is slow to load.

https://github.com/govau/uikit/blob/f69d6e71ca41c7159914d4cbaf8e60764c909c3b/packages/accordion/tests/site/index.html#L21-L23

**Comment by mikey0000** [comment]
Thank you so much for your help!!!

**Comment by alex-page** [comment]
After talking to @ndavison it seems it might be another issue. I'll leave this PR open for now and investigate offline.

**Pull request closed without merging**
