### PR TITLE
Added new focus styling for inputs and radio buttons

### PR DESCRIPTION
**Pull request by marcoalfonso**

### CODE REVIEW

**Comment by alex-page** [comment]
Hi Marco, thanks for the pull request. We are hoping to bundle this change in with a few other changes in the coming months.

**Comment by mgdhs** [comment]
I was sitting in a meeting so had a look at this one...

- `0px` doesn't need a unit
- should the vendor prefixes be handled by the compiler? What have other parts of the SASS done?
- `$uikit-light-focus` doesn't follow the naming convention or allow it to be overridden

Has this been tested in any way? Where did the colour come from?

**Comment by marcoalfonso** [comment]
Hi,
Yes I am using 0px as an override. That can be refactored.
I discussed with Alex about the naming convention and he said to just name it something so I followed the naming of the codepen he provided (https://codepen.io/treb/pen/wqBYNZ).
No it hasn't been tested, would be good if there was a guide of how to test changes :)

Hopefully the workflow for submitting pr's to uikit can be smoothed.

**Comment by alex-page** [comment]
Thanks for finding those @mgdhs. We are trying to encourage all contributions, so don't be alarmed if there are some issues.

We are investigating if we want to add a definition of done to pull requests. Research so far has told us that increasing a barrier of entry will decrease community engagement.

In terms of the colour, that has come out of some work which isn't ready to be implemented yet, the prototypes discussed above are an experiment.

**Comment by dominikwilkowski** [comment]
Hey thanks for the contribution. I will close this for now as we are about to roll out a new color system. Sorry for the extra work, we are trying hard to avoid that in the future. Roadmaps and the such will be out soon.

Thanks though

**Pull request closed without merging**
